#!/usr/bin/env python3
"""
generate_subfolder_claude.py — AgentForge context-scoping walker.

Walks a source tree, detects packages/modules, and generates a nested
`CLAUDE.md` for each one so that Claude Code loads only the active
subfolder's guidance into context (plus a slimmed root router).

Design notes
------------
- MODULAR codebases only. For legacy MONOLITHIC code (no package seams)
  use the guided path: `/scope-context --monolith` or `/legacy-audit`.
- Generated content lives between SCOPE:AUTO markers so hand-written notes
  outside the block are preserved on re-runs. Idempotent by design.
- Stdlib only (ast, pathlib, argparse, json). No third-party deps, no imports
  of the target code (safe on any repo).
- AgentForge-managed packages are SKIPPED. A package whose files are recorded
  in `agentic-assets/INSTALLED_MANIFEST.json` (e.g. the shipped
  `src/neuroedge_marketing/`) belongs to the installer, not the project: the
  installer content-checks it (`install.py --verify`) and an update rewrites it
  to the source copy. Writing a scope block into it made setup and update fight
  over the same file forever (a DRIFT right after every setup, undone by the
  next update). The walker documents the project's OWN modules; managed
  packages ship whatever context they need themselves.

Usage
-----
    python generate_subfolder_claude.py --root src --dry-run
    python generate_subfolder_claude.py --root src --router
    python generate_subfolder_claude.py --root packages --force

Exit codes: 0 ok, 2 nothing detected (likely monolithic — use guided path),
3 only AgentForge-managed packages detected (nothing of the project's to scope).
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

BEGIN = "<!-- SCOPE:AUTO:BEGIN — regenerated by generate_subfolder_claude.py; edit outside this block -->"
END = "<!-- SCOPE:AUTO:END -->"

# Directories that never carry meaningful scope context.
IGNORE_DIRS = {
    "__pycache__", ".git", ".venv", "venv", "node_modules", "test-results",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", "dist", "build",
    ".idea", ".vscode", "coverage", ".tox",
}
IGNORE_SUFFIXES = {".egg-info"}
TEST_DIR_NAMES = {"tests", "test", "__tests__"}
ENTRYPOINT_NAMES = {"cli.py", "__main__.py", "main.py", "app.py", "server.py"}


def _ignored(d: Path) -> bool:
    return d.name in IGNORE_DIRS or any(d.name.endswith(s) for s in IGNORE_SUFFIXES)


def _read(path: Path) -> str:
    """Read source as text, stripping a UTF-8 BOM (utf-8-sig) so ast.parse and
    json.loads don't choke on a leading \\ufeff."""
    return path.read_text(encoding="utf-8-sig", errors="replace")


@dataclass
class Module:
    path: Path
    root: Path
    kind: str  # "python" | "js"
    purpose: str = ""
    public_api: list[str] = field(default_factory=list)
    files: list[str] = field(default_factory=list)
    subpackages: list[str] = field(default_factory=list)
    entrypoints: list[str] = field(default_factory=list)
    has_tests: bool = False

    @property
    def rel(self) -> str:
        return self.path.relative_to(self.root).as_posix()

    @property
    def name(self) -> str:
        return self.path.name


# --------------------------------------------------------------------------- #
# Detection
# --------------------------------------------------------------------------- #
def is_python_pkg(d: Path) -> bool:
    return (d / "__init__.py").is_file()


def is_js_pkg(d: Path) -> bool:
    return (d / "package.json").is_file()


MANIFEST_REL = Path("agentic-assets") / "INSTALLED_MANIFEST.json"


def find_manifest(start: Path) -> Path | None:
    """The nearest `agentic-assets/INSTALLED_MANIFEST.json` at or above `start`.

    `--root` is normally `<project>/src`, so the manifest sits one level up; the
    upward walk also covers a deeper `--root`. None when no install is found.
    """
    for base in (start, *start.parents):
        candidate = base / MANIFEST_REL
        if candidate.is_file():
            return candidate
    return None


def load_managed_files(manifest: Path) -> tuple[Path, set[str]]:
    """(project root, project-relative POSIX paths) recorded by the installer.

    An unreadable or malformed manifest yields an empty set: the walker then
    behaves exactly as it did before managed-package skipping existed, which is
    the safe fallback for a tool that only ever writes marker-delimited blocks.
    """
    project = manifest.parent.parent
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return project, set()
    files = data.get("files") if isinstance(data, dict) else None
    if not isinstance(files, list):
        return project, set()
    return project, {f for f in files if isinstance(f, str)}


def managed_dirs(project: Path, managed_files: set[str]) -> set[Path]:
    """Resolved directories that directly contain an installer-managed file."""
    return {(project / rel).parent.resolve() for rel in managed_files}


def split_managed(modules: list[Module], skip_dirs: set[Path]) -> tuple[list[Module], list[Module]]:
    """(project modules to scope, AgentForge-managed modules to leave alone)."""
    own = [m for m in modules if m.path.resolve() not in skip_dirs]
    managed = [m for m in modules if m.path.resolve() in skip_dirs]
    return own, managed


def find_modules(root: Path, max_depth: int) -> list[Module]:
    """Every package-marked directory within max_depth becomes a scoped module.

    Skips ignored dirs and anything inside a test tree (a dir named tests/ etc.
    or nested beneath one).
    """
    modules: list[Module] = []
    for d in sorted(root.rglob("*")):
        if not d.is_dir():
            continue
        parts = d.relative_to(root).parts
        depth = len(parts)
        if depth > max_depth:
            continue
        # skip if any path segment is an ignored dir, egg-info, or a test tree
        if any(
            part in IGNORE_DIRS
            or part in TEST_DIR_NAMES
            or any(part.endswith(s) for s in IGNORE_SUFFIXES)
            for part in parts
        ):
            continue
        if is_python_pkg(d):
            modules.append(_scan_python(d, root))
        elif is_js_pkg(d):
            modules.append(_scan_js(d, root))
    return modules


# --------------------------------------------------------------------------- #
# Python scanning (via ast — never imports target code)
# --------------------------------------------------------------------------- #
def _scan_python(d: Path, root: Path) -> Module:
    m = Module(path=d, root=root, kind="python")
    init = d / "__init__.py"
    try:
        tree = ast.parse(_read(init))
        m.purpose = _first_line(ast.get_docstring(tree) or "")
        m.public_api = _python_public_api(tree)
    except (SyntaxError, OSError):
        pass

    for child in sorted(d.iterdir()):
        if child.is_dir() and not _ignored(child):
            if child.name in TEST_DIR_NAMES:
                m.has_tests = True
            elif is_python_pkg(child) or is_js_pkg(child):
                m.subpackages.append(child.name)
        elif child.is_file() and child.suffix == ".py" and child.name != "__init__.py":
            m.files.append(child.name)
            if child.name in ENTRYPOINT_NAMES or _has_main_guard(child):
                m.entrypoints.append(child.name)
    return m


def _python_public_api(tree: ast.Module) -> list[str]:
    # Prefer an explicit __all__.
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == "__all__":
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        return [e.value for e in node.value.elts
                                if isinstance(e, ast.Constant) and isinstance(e.value, str)]
    # Otherwise: re-exports + top-level defs/classes.
    names: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.level:  # from .x import Y
            names.extend(a.asname or a.name for a in node.names if a.name != "*")
        elif isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                names.append(node.name)
    # de-dup, keep order
    seen: set[str] = set()
    return [n for n in names if not (n in seen or seen.add(n))]


def _has_main_guard(f: Path) -> bool:
    try:
        return "__main__" in _read(f)
    except OSError:
        return False


# --------------------------------------------------------------------------- #
# JS/TS scanning
# --------------------------------------------------------------------------- #
def _scan_js(d: Path, root: Path) -> Module:
    m = Module(path=d, root=root, kind="js")
    try:
        pkg = json.loads(_read(d / "package.json"))
        m.purpose = _first_line(pkg.get("description", ""))
        main = pkg.get("main") or pkg.get("module")
        if main:
            m.entrypoints.append(main)
        if "scripts" in pkg:
            m.public_api = sorted(pkg["scripts"].keys())
    except (ValueError, OSError):
        pass
    for child in sorted(d.iterdir()):
        if child.is_dir() and not _ignored(child):
            if child.name in TEST_DIR_NAMES:
                m.has_tests = True
            elif child.name in ("src", "lib", "components"):
                m.subpackages.append(child.name)
        elif child.is_file() and child.suffix in (".ts", ".tsx", ".js", ".jsx"):
            m.files.append(child.name)
    return m


def _first_line(s: str) -> str:
    return s.strip().splitlines()[0].strip() if s.strip() else ""


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def render_module(m: Module) -> str:
    api = ", ".join(f"`{a}`" for a in m.public_api[:20]) or "_none detected — inspect the source_"
    entry = ", ".join(f"`{e}`" for e in m.entrypoints) or "—"
    subs = ", ".join(f"`{s}/`" for s in m.subpackages) or "—"
    files = "\n".join(f"| `{f}` | |" for f in m.files[:30]) or "| _(no top-level files)_ | |"
    purpose = m.purpose or "_TODO: one-line purpose of this module._"

    return f"""{BEGIN}
# `{m.name}` — module context

> **Scope rule.** When you are working in `{m.rel}`, treat this module as your
> working set. Do **not** open other modules' internals to understand them —
> use their **public surface** (below / documented in the root `CLAUDE.md`).
> If you genuinely need a fact from another module, **delegate to an `Explore`
> subagent** so its files don't fill this context window.

**Purpose:** {purpose}

**Public surface (safe for other modules to depend on):** {api}

**Entry points:** {entry} &nbsp;•&nbsp; **Sub-packages:** {subs} &nbsp;•&nbsp; **Tests:** {"yes" if m.has_tests else "none detected"}

**Top-level files** (fill the second column with a one-line role):

| File | Role |
|---|---|
{files}

*Generated by AgentForge `generate_subfolder_claude.py`. Edit prose freely —
just keep it outside the SCOPE:AUTO markers, or it is overwritten on re-run.*
{END}
"""


def render_router(modules: list[Module], root: Path) -> str:
    rows = "\n".join(
        f"| [`{m.rel}/`]({m.rel}/CLAUDE.md) | {m.purpose or '_—_'} |"
        for m in sorted(modules, key=lambda x: x.rel)
    )
    return f"""{BEGIN}
## Module map — load only what you touch

Each module below has its own `CLAUDE.md` that Claude Code loads **only** when
you work inside it. Keep this root file lean: project-wide rules go here,
module detail goes in the nested files.

| Module | Purpose |
|---|---|
{rows}

**Cross-module rule:** depend on another module only through its documented
public surface. To learn how another module works, dispatch an `Explore`
subagent (it returns a summary, not the files) rather than reading it here.
{END}
"""


# --------------------------------------------------------------------------- #
# Writing (marker-aware, idempotent)
# --------------------------------------------------------------------------- #
def write_block(target: Path, block: str, *, force: bool, dry_run: bool) -> str:
    existing = target.read_text(encoding="utf-8") if target.exists() else None

    if existing is None:
        action = "create"
        new = block
    elif BEGIN in existing and END in existing:
        pre = existing[: existing.index(BEGIN)]
        post = existing[existing.index(END) + len(END):]
        new = pre + block.strip() + post
        action = "update-block"
    elif force:
        new = block
        action = "overwrite"
    else:
        return f"skip (exists, no markers — use --force): {target}"

    if dry_run:
        return f"[dry-run] {action}: {target}"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(new, encoding="utf-8")
    return f"{action}: {target}"


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def main(
    argv: list[str] | None = None,
    *,
    managed: tuple[Path, set[str]] | None = None,
) -> int:
    """CLI entry point.

    `managed` is (project root, project-relative managed file paths). In-process
    callers that already know the install plan pass it — setup does, from
    `install._managed_files()`, which also works under `--dry-run` before any
    manifest has been written. Omitted, the walker reads the nearest
    `agentic-assets/INSTALLED_MANIFEST.json` at or above `--root`.
    """
    p = argparse.ArgumentParser(description="Generate nested CLAUDE.md files by walking a modular source tree.")
    p.add_argument("--root", default="src", help="source root to walk (default: src)")
    p.add_argument("--max-depth", type=int, default=2,
                   help="how many levels below root to scope (default: 2; use 1 for top-level packages only)")
    p.add_argument("--router", action="store_true", help="also (re)write the root CLAUDE.md module map")
    p.add_argument("--router-path", default="CLAUDE.md", help="path to root router file (default: CLAUDE.md)")
    p.add_argument("--force", action="store_true", help="overwrite files that exist without SCOPE:AUTO markers")
    p.add_argument("--dry-run", action="store_true", help="print planned actions, write nothing")
    args = p.parse_args(argv)

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"error: root not found: {root}", file=sys.stderr)
        return 2

    if managed is None:
        manifest = find_manifest(root)
        managed = load_managed_files(manifest) if manifest else None
    skip_dirs = managed_dirs(*managed) if managed else set()
    modules, skipped = split_managed(find_modules(root, args.max_depth), skip_dirs)

    for m in skipped:
        print(f"  skip (AgentForge-managed — owned by the installer): {m.path}")
    if not modules and skipped:
        print(f"Only AgentForge-managed packages under {root} — nothing of the project's to scope.")
        return 3
    if not modules:
        print(f"No packages detected under {root}.")
        print("This looks MONOLITHIC (no __init__.py / package.json seams).")
        print("Use the guided path:  /scope-context --monolith   (or /legacy-audit)")
        return 2

    print(f"Detected {len(modules)} module(s) under {root}:\n")
    for m in modules:
        target = m.path / "CLAUDE.md"
        print("  " + write_block(target, render_module(m), force=args.force, dry_run=args.dry_run))

    if args.router:
        router = Path(args.router_path).resolve()
        print("\n" + write_block(router, render_router(modules, root), force=args.force, dry_run=args.dry_run))

    if args.dry_run:
        print("\n(dry-run — no files written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
