"""A tool-server protocol face, so a tool-server-backed capability is rehearsable (FR-10).

Every other face in this simulator answers an **address**: a path, a role and a capability, a topic.
A tool server does not work that way. A client connects, negotiates, asks the server *what tools do
you have*, and only then calls one. Standing an ordinary HTTP stub in front of that client is worse
than having no face at all -- the client's very first message fails, and it fails with a protocol
error rather than with anything an author can act on. So this face speaks the three messages that
matter:

    initialize    ->  who you are talking to, and which protocol version
    tools/list    ->  the surface this server offers
    tools/call    ->  one call, answered from a fixture

🔴 **The advertised surface is DERIVED, never authored, and that is the whole point of the face.**
A hand-written tool list can say anything: it can advertise a tool the real server does not have, or
describe one with the wrong arguments, and a rehearsal against it would pass while production fails
on the first call. The list is therefore generated by the host from whatever it discovered from the
real servers, and this module **refuses a file that does not declare that provenance**
(:data:`DERIVED_SOURCE`). A simulator that can advertise more than the real thing is not a
simulator; it is a second implementation with no tests.

🔴 **Answers reuse :class:`~neuro_sim.fixtures.FixtureEntry` -- one store, one resolution chain, no
second vocabulary.** A server id is a role and a tool name is a capability, so
``(server_id, caller, tool_name)`` is the chain an author has already learned:
``returns`` xor ``sequence``, ``faults``, caller-scoped. Inventing a parallel shape for this face
would mean two ways to say "answer differently on the second ask", which is one more than any
author wants to know about.

**Two files, and the split is deliberate.** ``servers.json`` is generated and must not be edited;
``responses.json`` is authored and must not be generated. Keeping them apart means a regeneration
never overwrites an author's fixtures, and an author never quietly widens the advertised surface.
"""

from __future__ import annotations

import json
import random
import threading
import time
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path
from typing import Any
from typing import Optional

from .fixtures import FaultConfig
from .fixtures import FixtureEntry
from .fixtures import FixtureStore
from .fixtures import ManifestError
from .fixtures import SimManifest
from .fixtures import SimRole

#: The reserved first path segment for this face. A name rather than a bare literal so the
#: reservation is greppable from the server, the fixture model and the bundle that points at it.
MCP_PATH_PREFIX = "mcp"

#: The generated half of the face, inside a system's ``mcp`` directory.
SERVERS_FILENAME = "servers.json"

#: The authored half. Named apart from ``servers.json`` so a regeneration cannot touch it.
RESPONSES_FILENAME = "responses.json"

#: What a generated ``servers.json`` must declare about where it came from. A file without it is
#: refused: see the module docstring: an authored tool list can advertise anything.
DERIVED_SOURCE = "discovery-cache"

#: Protocol versions this face will agree to. A client names one; if it is known it is echoed back,
#: because agreeing to the client's version is what the protocol asks for. An unknown one gets
#: :data:`DEFAULT_PROTOCOL_VERSION` rather than a refusal -- a version mismatch is the client's to
#: resolve, and a stub that hangs up on it teaches nothing.
KNOWN_PROTOCOL_VERSIONS = ("2024-11-05", "2025-03-26", "2025-06-18")

#: What this face answers with when the client names no version, or one it does not know.
DEFAULT_PROTOCOL_VERSION = "2025-06-18"

#: JSON-RPC error codes, spelled once.
METHOD_NOT_FOUND = -32601
INVALID_PARAMS = -32602


class McpFaceError(ValueError):
    """A tool-server file that cannot be read, or that claims a provenance it does not have.

    Distinct from "no file": absent is legal and means "this system fronts no tool server", so a
    scenario that has not configured one still starts. Unreadable is not -- a malformed file
    silently treated as empty would report "no tools advertised" for a file full of them.
    """


@dataclass(frozen=True)
class McpTool:
    """One tool the face advertises, exactly as the host discovered it from the real server."""

    server_id: str
    tool_name: str
    description: str = ""
    input_schema: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.server_id:
            raise McpFaceError("a discovered tool names no server_id")
        if not self.tool_name:
            raise McpFaceError(f"a discovered tool of server '{self.server_id}' names no tool_name")

    @classmethod
    def from_dict(cls, raw: Any) -> McpTool:
        """Decode one entry of a generated server's ``tools`` list."""
        if not isinstance(raw, dict):
            raise McpFaceError(f"a discovered tool is {type(raw).__name__}, not an object")
        unknown = sorted(set(raw) - {"server_id", "tool_name", "description", "input_schema"})
        if unknown:
            raise McpFaceError(f"discovered tool has unrecognised key(s) {unknown}")
        schema = raw.get("input_schema") or {}
        if not isinstance(schema, dict):
            raise McpFaceError(
                f"discovered tool '{raw.get('tool_name')}' has an input_schema that is "
                f"{type(schema).__name__}, not an object"
            )
        return cls(
            server_id=str(raw.get("server_id") or ""),
            tool_name=str(raw.get("tool_name") or ""),
            description=str(raw.get("description", "")),
            input_schema=dict(schema),
        )

    def advertised(self) -> dict:
        """The wire shape of one entry in a ``tools/list`` result."""
        return {"name": self.tool_name, "description": self.description, "inputSchema": dict(self.input_schema)}


@dataclass(frozen=True)
class McpServer:
    """One tool server the face stands in for.

    :attr:`address` is the **real** server's address, carried so the bundle's endpoint overlay has
    something to replace and so a reader can see which production system this stub is standing in
    for. 🔴 Nothing in this module ever dials it. The address a caller reaches is this simulator's
    own, handed out by the runner -- the request body never names a destination, because a stub that
    let a request choose its own upstream would be an open proxy wearing a fixture's clothes.
    """

    id: str
    address: str = ""
    description: str = ""
    tools: tuple = ()

    def __post_init__(self) -> None:
        if not self.id:
            raise McpFaceError("a tool server has no id")


def _decode_servers(loaded: Any, *, where: str) -> tuple:
    """Validate a generated ``servers.json`` and return its :class:`McpServer` entries."""
    if not isinstance(loaded, dict):
        raise McpFaceError(f"tool-server file '{where}' must be an object, not {type(loaded).__name__}")
    unknown = sorted(set(loaded) - {"source", "generated_by", "generated_at", "servers"})
    if unknown:
        raise McpFaceError(f"tool-server file '{where}' has unrecognised key(s) {unknown}")
    source = str(loaded.get("source") or "")
    if source != DERIVED_SOURCE:
        # 🔴 The refusal the face exists for. `source` is not decoration: it is the only evidence
        # in the file that its tool list came from the real servers rather than from someone's
        # memory of them. Reading a file without it would make the advertised surface authored,
        # and an authored surface can promise tools production does not have.
        raise McpFaceError(
            f"tool-server file '{where}' declares source {source!r}, not {DERIVED_SOURCE!r}. This "
            "file is generated from what was discovered from the real servers and must not be "
            "hand-authored -- a hand-written tool list can advertise tools, or argument shapes, "
            "that production does not have, and a rehearsal against it passes while the real call "
            f"fails. Regenerate it. Author answers in '{RESPONSES_FILENAME}' instead."
        )
    raw_servers = loaded.get("servers")
    if not isinstance(raw_servers, list):
        raise McpFaceError(f"tool-server file '{where}' must hold a 'servers' list")

    servers: list[McpServer] = []
    seen: set = set()
    for entry in raw_servers:
        if not isinstance(entry, dict):
            raise McpFaceError(f"tool-server file '{where}': a server is {type(entry).__name__}, not an object")
        extra = sorted(set(entry) - {"id", "address", "description", "tools"})
        if extra:
            raise McpFaceError(f"tool-server file '{where}': server has unrecognised key(s) {extra}")
        server_id = str(entry.get("id") or "")
        if server_id in seen:
            raise McpFaceError(
                f"tool-server file '{where}' declares server '{server_id}' twice. Refused rather "
                "than merged -- two entries for one id are two answers to 'what does this server "
                "offer', and picking one silently is how an author edits the list that is not "
                "being served."
            )
        seen.add(server_id)
        # 🔴 The enclosing server wins: a tool naming a different `server_id` than the block it sits
        # in would advertise itself under one server and be looked up under another, which is a
        # tool that lists and then cannot be called.
        tools = tuple(
            McpTool.from_dict({**tool, "server_id": server_id} if isinstance(tool, dict) else tool)
            for tool in entry.get("tools", ())
        )
        names = [tool.tool_name for tool in tools]
        if len(set(names)) != len(names):
            duplicated = sorted({name for name in names if names.count(name) > 1})
            raise McpFaceError(f"tool-server file '{where}': server '{server_id}' advertises {duplicated} twice")
        servers.append(
            McpServer(
                id=server_id,
                address=str(entry.get("address", "")),
                description=str(entry.get("description", "")),
                tools=tools,
            )
        )
    return tuple(servers)


def load_mcp_servers(directory: Optional[Path]) -> tuple:
    """Read a system's generated ``servers.json``, or nothing when it has none."""
    if directory is None:
        return ()
    path = Path(directory) / SERVERS_FILENAME
    if not path.exists():
        return ()
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise McpFaceError(f"tool-server file '{path}' is unreadable: {exc}") from exc
    return _decode_servers(loaded, where=str(path))


def load_mcp_responses(directory: Optional[Path]) -> dict:
    """Read a system's authored ``responses.json`` as ``{server_id: (FixtureEntry, ...)}``.

    The file is a flat list; each entry names the ``server_id`` it answers for and is otherwise an
    ordinary fixture. Flat rather than nested per server because the nesting buys one saved key per
    entry and costs the author a second shape to remember.
    """
    if directory is None:
        return {}
    path = Path(directory) / RESPONSES_FILENAME
    if not path.exists():
        return {}
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise McpFaceError(f"tool-server responses file '{path}' is unreadable: {exc}") from exc
    entries = loaded.get("responses") if isinstance(loaded, dict) else loaded
    if not isinstance(entries, list):
        raise McpFaceError(
            f"tool-server responses file '{path}' must hold a list of responses, or an object with "
            "a 'responses' list"
        )
    by_server: dict = {}
    for raw in entries:
        if not isinstance(raw, dict):
            raise McpFaceError(f"tool-server responses file '{path}': a response is {type(raw).__name__}")
        server_id = str(raw.get("server_id") or "")
        if not server_id:
            raise McpFaceError(f"tool-server responses file '{path}': a response names no server_id")
        fixture = {key: value for key, value in raw.items() if key != "server_id"}
        # 🔴 `tool_name` is spelled `capability` inside the store, because that is what the chain
        # is keyed on. Translated here, at the file boundary, rather than asking the author to use
        # the store's word for a thing the protocol calls a tool.
        if "tool_name" in fixture:
            if "capability" in fixture:
                # Refused rather than resolved by precedence. Two names for one key is how an
                # author edits the value that is not being served and concludes the sim ignores
                # edits -- the same refusal the duplicate-key rules elsewhere in this asset make.
                raise McpFaceError(
                    f"tool-server responses file '{path}', server '{server_id}': a response "
                    "declares both `tool_name` and `capability`, which name the same thing. Keep "
                    "`tool_name` -- it is the protocol's word and the one this file documents."
                )
            fixture["capability"] = fixture.pop("tool_name")
        try:
            by_server.setdefault(server_id, []).append(FixtureEntry.from_dict(fixture))
        except ManifestError as exc:
            raise McpFaceError(f"tool-server responses file '{path}', server '{server_id}': {exc}") from exc
    return {server_id: tuple(fixtures) for server_id, fixtures in by_server.items()}


class McpFace:
    """Answers the three protocol messages for every tool server one simulator fronts.

    Transport-free on purpose: :meth:`handle` takes a decoded request object and returns
    ``(status, payload)``, so the same face can be driven by the stub server, by a test, or by any
    other carrier without the protocol logic knowing which.
    """

    def __init__(  # pylint: disable=too-many-arguments
        self,
        servers: tuple = (),
        responses: Optional[dict] = None,
        *,
        name: str = "sim",
        rng: Optional[Any] = None,
        rng_lock: Optional[Any] = None,
    ) -> None:
        self._servers: dict = {}
        for server in servers:
            if server.id in self._servers:
                raise McpFaceError(
                    f"two systems both front tool server '{server.id}'. Refused rather than merged: "
                    "one server answering from two files is free to answer two ways."
                )
            self._servers[server.id] = server
        self.name = name
        unknown = sorted(set(responses or {}) - set(self._servers))
        if unknown:
            raise McpFaceError(
                f"responses are authored for tool server(s) {unknown}, which no system declares. "
                "Refused rather than ignored -- a fixture nobody can reach reads as configured and "
                "answers nothing, which is the silent half of a loud miss."
            )
        # One store, keyed (server_id, caller, tool_name) -- the fixture chain, renamed nowhere.
        roles = tuple(
            SimRole(id=server_id, fixtures=fixtures) for server_id, fixtures in sorted((responses or {}).items())
        )
        self._store = FixtureStore(SimManifest(scenario=name, roles=roles))
        #: Which tools of which server have an authored answer. Kept here rather than read back out
        #: of the store, so a miss can name what IS configured without reaching into its internals.
        self._answered: dict = {
            server_id: tuple(sorted({fixture.capability for fixture in fixtures}))
            for server_id, fixtures in (responses or {}).items()
        }
        # Seeded from the run when the runner supplies one, so a flaky tool server is exactly as
        # flaky on every run with the same seed -- the property that makes fault injection usable in
        # a regression suite and not only in a demo. `random.Random` is not thread-safe and the
        # carrier serves each connection on its own thread, so the draw is taken under a lock.
        self._rng = rng if rng is not None else random.Random(0)  # nosec B311 - fixtures, not crypto
        self._rng_lock = rng_lock if rng_lock is not None else threading.Lock()

    def server_ids(self) -> tuple:
        """Every tool server this face stands in for. Named in an error so a miss says what is live."""
        return tuple(sorted(self._servers))

    def tool_names(self, server_id: str) -> tuple:
        """What one server advertises. Named in an unknown-tool error for the same reason."""
        server = self._servers.get(server_id)
        return tuple(tool.tool_name for tool in server.tools) if server is not None else ()

    def knows(self, server_id: str) -> bool:
        """Whether this face fronts that server at all."""
        return server_id in self._servers

    # ------------------------------------------------------------------ protocol

    def handle(self, server_id: str, message: Any, caller: str = "") -> tuple:
        """One protocol message. Returns ``(http_status, payload)``; ``payload`` ``None`` means
        *nothing to send* -- the answer to a notification, which the protocol forbids replying to.
        """
        if not isinstance(message, dict):
            return 400, self._error(None, INVALID_PARAMS, f"request is {type(message).__name__}, not an object")
        method = str(message.get("method") or "")
        request_id = message.get("id")
        # 🔴 Checked BEFORE the notification short-circuit, deliberately. A message addressed to a
        # server this simulator does not front is a misconfiguration whichever kind of message it
        # is, and answering a notification 202 would record it as accepted -- the "declared signal
        # source that never fires" shape, which is the defect this asset's loaders exist to catch.
        if not self.knows(server_id):
            return 404, self._error(
                request_id,
                INVALID_PARAMS,
                f"no tool server '{server_id}' is simulated here; this simulator fronts "
                f"{list(self.server_ids())}",
            )
        # `is None` rather than a falsy test: `"id": 0` is a legal request id, and treating it as a
        # notification would drop the answer to a real call.
        if request_id is None:
            # A notification. Accepted and dropped: the client is telling, not asking, and a body
            # here would be a response to something that has no response.
            return 202, None
        if method == "initialize":
            return 200, self._result(request_id, self._initialize(server_id, message.get("params")))
        if method == "tools/list":
            return 200, self._result(request_id, {"tools": [tool.advertised() for tool in self._tools(server_id)]})
        if method == "ping":
            return 200, self._result(request_id, {})
        if method == "tools/call":
            return self._call(server_id, request_id, message.get("params"), caller)
        return 200, self._error(
            request_id,
            METHOD_NOT_FOUND,
            f"this face answers initialize, tools/list and tools/call; it was asked for {method!r}",
        )

    def _tools(self, server_id: str) -> tuple:
        return self._servers[server_id].tools

    def _initialize(self, server_id: str, params: Any) -> dict:
        requested = str((params or {}).get("protocolVersion") or "") if isinstance(params, dict) else ""
        version = requested if requested in KNOWN_PROTOCOL_VERSIONS else DEFAULT_PROTOCOL_VERSION
        return {
            "protocolVersion": version,
            "capabilities": {"tools": {"listChanged": False}},
            # 🔴 Named as a simulator, deliberately. A stub that introduces itself under the real
            # server's name is a stub whose logs are indistinguishable from production's.
            "serverInfo": {"name": f"simulated:{server_id}", "version": "0"},
        }

    def _call(self, server_id: str, request_id: Any, params: Any, caller: str) -> tuple:
        if not isinstance(params, dict):
            return 200, self._error(request_id, INVALID_PARAMS, "tools/call params must be an object")
        tool_name = str(params.get("name") or "")
        if tool_name not in self.tool_names(server_id):
            # 🔴 A JSON-RPC error, not an `isError` result, and the difference is the point of this
            # face: the real server does not have this tool either, so the honest answer is the one
            # the real server would give. An `isError` result would say "the tool ran and failed",
            # which is a rehearsal quietly teaching that the tool exists.
            return 200, self._error(
                request_id,
                INVALID_PARAMS,
                f"tool server '{server_id}' has no tool '{tool_name}'; it offers "
                f"{list(self.tool_names(server_id))}",
            )
        # 🔴 The tool's own arguments reach resolution, so an MCP-served capability can be scoped
        # by what was asked exactly as an HTTP-served one is. MCP carries them in `params.arguments`
        # by the protocol; leaving them out here would have made `matches` work on one face of the
        # same simulator and not the other, which is the sort of split an author discovers by
        # authoring a fixture that never fires.
        arguments = params.get("arguments")
        answered = self._store.answer(
            server_id, tool_name, caller, arguments if isinstance(arguments, dict) else None
        )
        if answered is None:
            # Loud, and it names the two facts a person needs: which key missed, and what the
            # server does offer. Never an empty success -- see the fixture store's own rule.
            return 200, self._tool_error(
                request_id,
                f"no response is configured for tool '{tool_name}' on server '{server_id}'"
                + (f" for caller '{caller}'" if caller else "")
                + f". Tools of this server with an authored answer: {list(self._answered.get(server_id, ()))}",
            )
        payload, faults = answered
        return 200, self._faulted(request_id, payload, faults, f"{server_id}'.'{tool_name}")

    def _faulted(self, request_id: Any, payload: dict, faults: FaultConfig, where: str) -> dict:
        """Apply the fixture's declared faults, in the same order the HTTP face applies them."""
        if faults.delay_seconds:
            time.sleep(faults.delay_seconds)
        if self._roll(faults.error_rate):
            return self._tool_error(request_id, f"injected fault on '{where}'")
        if faults.malformed:
            # Deliberately not the declared shape -- a bare string where the schema promised an
            # object, which is what a misbehaving upstream actually sends.
            return self._result(request_id, self._content("this is not the declared object shape"))
        return self._result(request_id, self._content(payload))

    def _roll(self, error_rate: float) -> bool:
        """One atomic draw against the run's seeded RNG -- the stub server's rule, applied here."""
        if not error_rate:
            return False
        with self._rng_lock:
            return self._rng.random() < error_rate

    # ------------------------------------------------------------------ wire shapes

    @staticmethod
    def _content(payload: Any) -> dict:
        """A tool result: the answer as text, plus the object itself where the protocol allows it.

        The text is what every client can read; ``structuredContent`` is what a client that
        understands it can parse without re-decoding a string. Both carry the same value, so a
        client reading either sees the fixture.
        """
        if isinstance(payload, str):
            return {"content": [{"type": "text", "text": payload}], "isError": False}
        text = json.dumps(payload, ensure_ascii=False, default=str)
        result: dict = {"content": [{"type": "text", "text": text}], "isError": False}
        if isinstance(payload, dict):
            result["structuredContent"] = payload
        return result

    @staticmethod
    def _result(request_id: Any, result: Any) -> dict:
        return {"jsonrpc": "2.0", "id": request_id, "result": result}

    @staticmethod
    def _error(request_id: Any, code: int, message: str) -> dict:
        return {"jsonrpc": "2.0", "id": request_id, "error": {"code": code, "message": message}}

    @classmethod
    def _tool_error(cls, request_id: Any, message: str) -> dict:
        """A call that reached the tool and failed -- distinct from one the server could not route."""
        return cls._result(request_id, {"content": [{"type": "text", "text": message}], "isError": True})
